import type { DataExportCatalogItem, DataExportFilterDefinition } from './data-export.types';

const DATA_EXPORT_FILTERS = {
  province: { key: 'province', label: 'จังหวัด', control: 'TEXT', placeholder: 'ชื่อจังหวัด' },
  district: {
    key: 'district',
    label: 'อำเภอ/เขต',
    control: 'TEXT',
    placeholder: 'ชื่ออำเภอหรือเขต',
    dependsOn: 'province',
  },
  subDistrict: {
    key: 'subDistrict',
    label: 'ตำบล/แขวง',
    control: 'TEXT',
    placeholder: 'ชื่อตำบลหรือแขวง',
    dependsOn: 'district',
  },
  schoolId: {
    key: 'schoolId',
    label: 'รหัสโรงเรียน',
    control: 'INTEGER',
    valueType: 'INTEGER',
  },
  academicYear: { key: 'academicYear', label: 'ปีการศึกษา', control: 'INTEGER' },
  semester: {
    key: 'semester',
    label: 'ภาคเรียน',
    control: 'SELECT',
    options: [
      { value: '1', label: 'ภาคเรียนที่ 1' },
      { value: '2', label: 'ภาคเรียนที่ 2' },
    ],
  },
  grade: { key: 'grade', label: 'ระดับชั้น', control: 'TEXT', placeholder: 'เช่น ป.1' },
  room: {
    key: 'room',
    label: 'ห้อง',
    control: 'TEXT',
    placeholder: 'เช่น 1',
    dependsOn: 'grade',
  },
  dateFrom: { key: 'dateFrom', label: 'ตั้งแต่วันที่', control: 'DATE' },
  dateTo: { key: 'dateTo', label: 'ถึงวันที่', control: 'DATE' },
  status: { key: 'status', label: 'สถานะ', control: 'TEXT', placeholder: 'รหัสสถานะ' },
  structureStatus: {
    key: 'structureStatus',
    label: 'สถานะโครงสร้าง',
    control: 'SELECT',
    options: [
      { value: 'ACTIVE', label: 'ใช้งาน' },
      { value: 'INACTIVE', label: 'ไม่ใช้งาน' },
    ],
  },
  assignmentKind: {
    key: 'assignmentKind',
    label: 'ประเภทงานสอน',
    control: 'SELECT',
    options: [
      { value: 'HOMEROOM', label: 'ครูประจำชั้น' },
      { value: 'SUBJECT', label: 'ครูประจำวิชา' },
    ],
  },
  concernLevel: {
    key: 'concernLevel',
    label: 'ระดับข้อสังเกต',
    control: 'SELECT',
    options: [
      { value: 'NOTE', label: 'บันทึกทั่วไป' },
      { value: 'WATCH', label: 'เฝ้าระวัง' },
      { value: 'CONCERN', label: 'น่ากังวล' },
    ],
  },
  riskTier: {
    key: 'riskTier',
    label: 'ระดับความเสี่ยง',
    control: 'SELECT',
    options: [
      { value: 'HIGH', label: 'สูง' },
      { value: 'MEDIUM', label: 'ปานกลาง' },
      { value: 'LOW', label: 'ต่ำ' },
      { value: 'WATCH', label: 'เฝ้าระวัง' },
      { value: 'NORMAL', label: 'ปกติ' },
    ],
  },
} as const satisfies Record<string, DataExportFilterDefinition>;

function filterDefinitions(
  ...keys: Array<keyof typeof DATA_EXPORT_FILTERS>
): DataExportFilterDefinition[] {
  return keys.map((key) => DATA_EXPORT_FILTERS[key]);
}

export const DATA_EXPORT_CATALOG: DataExportCatalogItem[] = [
  {
    code: 'student_roster_basic',
    label: 'รายชื่อนักเรียนพื้นฐาน',
    description:
      'รายชื่อนักเรียนตามทะเบียนปัจจุบันแบบลดข้อมูลอ่อนไหว ไม่มีเลขบัตร ที่อยู่ ช่องทางติดต่อ หรือพิกัด',
    sensitivityClass: 'OPERATIONAL',
    formats: ['CSV'],
    fieldBundles: [
      {
        code: 'basic',
        label: 'ข้อมูลพื้นฐาน',
        description: 'รหัสอ้างอิงนักเรียน ชื่อ โรงเรียน ชั้น ห้อง และสถานะการเรียน',
      },
    ],
    supportedFilters: ['province', 'district', 'subDistrict', 'schoolId', 'grade', 'room'],
    filterDefinitions: filterDefinitions(
      'province',
      'district',
      'subDistrict',
      'schoolId',
      'grade',
      'room',
    ),
    requiredPermissions: ['export-data', 'students'],
    purposePolicy: 'OPTIONAL',
    deliveryMode: 'ASYNC_JOB',
    status: 'AVAILABLE',
  },
  {
    code: 'student_pii',
    label: 'ส่งออกข้อมูลนักเรียนที่มี PII',
    description:
      'ใช้ workflow เดิมของหน้ารายชื่อนักเรียน: purpose, approval, mask default, TTL และ one-time download',
    sensitivityClass: 'SENSITIVE_PII',
    formats: ['CSV'],
    fieldBundles: [
      {
        code: 'existing-student-pii-workflow',
        label: 'ตามคำขอส่งออกเดิม',
        description: 'field set ถูกควบคุมโดย workflow /students/export เดิม',
      },
    ],
    supportedFilters: ['studentListFilters'],
    filterDefinitions: [],
    requiredPermissions: ['export-data', 'students'],
    purposePolicy: 'EXISTING_WORKFLOW',
    deliveryMode: 'EXISTING_WORKFLOW',
    workflowPath: '/students/export',
    status: 'AVAILABLE',
  },
  {
    code: 'student_risk',
    label: 'ความเสี่ยงนักเรียน',
    description:
      'ระดับความเสี่ยงและตัวชี้วัดจาก risk profile โดยไม่รวมที่อยู่ พิกัด เลขบัตร หรือข้อมูลลับ',
    sensitivityClass: 'SENSITIVE_OPERATIONAL',
    formats: ['CSV'],
    fieldBundles: [
      {
        code: 'risk-summary',
        label: 'สรุปความเสี่ยง',
        description: 'risk tier, attendance indicators, active case count และ as-of',
      },
    ],
    supportedFilters: [
      'province',
      'district',
      'subDistrict',
      'schoolId',
      'grade',
      'room',
      'riskTier',
    ],
    filterDefinitions: filterDefinitions(
      'province',
      'district',
      'subDistrict',
      'schoolId',
      'grade',
      'room',
      'riskTier',
    ),
    requiredPermissions: ['export-data', 'dashboard'],
    purposePolicy: 'REQUIRED_CODE_AND_NOTE',
    deliveryMode: 'ASYNC_JOB',
    status: 'AVAILABLE',
  },
  {
    code: 'attendance_summary',
    label: 'สรุปการมาเรียน',
    description: 'อัตรามา/ขาด/สายแบบ aggregate ตามช่วงเวลาและขอบเขตสิทธิ์',
    sensitivityClass: 'AGGREGATE',
    formats: ['CSV'],
    fieldBundles: [
      {
        code: 'daily-summary',
        label: 'รายวัน',
        description: 'สรุปจำนวนและอัตราตามวันโดยไม่รวมข้อมูล PII รายคน',
      },
    ],
    supportedFilters: [
      'province',
      'district',
      'subDistrict',
      'schoolId',
      'grade',
      'room',
      'dateRange',
    ],
    filterDefinitions: filterDefinitions(
      'province',
      'district',
      'subDistrict',
      'schoolId',
      'grade',
      'room',
      'dateFrom',
      'dateTo',
    ),
    requiredPermissions: ['export-data'],
    purposePolicy: 'OPTIONAL',
    deliveryMode: 'ASYNC_JOB',
    status: 'AVAILABLE',
  },
  {
    code: 'case_summary',
    label: 'สรุปเคสติดตามนักเรียน',
    description: 'จำนวนเคสตามสถานะ SLA พื้นที่ และช่วงเวลา โดยไม่รวมบันทึกละเอียด',
    sensitivityClass: 'AGGREGATE',
    formats: ['CSV'],
    fieldBundles: [
      {
        code: 'status-summary',
        label: 'สรุปสถานะ',
        description: 'จำนวนเคสตามสถานะและ SLA bucket',
      },
    ],
    supportedFilters: ['province', 'district', 'subDistrict', 'schoolId', 'status', 'dateRange'],
    filterDefinitions: filterDefinitions(
      'province',
      'district',
      'subDistrict',
      'schoolId',
      'status',
      'dateFrom',
      'dateTo',
    ),
    requiredPermissions: ['export-data', 'dashboard'],
    purposePolicy: 'OPTIONAL',
    deliveryMode: 'ASYNC_JOB',
    status: 'AVAILABLE',
  },
  {
    code: 'case_operational',
    label: 'เคสติดตามนักเรียนเชิงปฏิบัติการ',
    description:
      'ข้อมูลติดตามงานเคสแบบลดข้อมูลอ่อนไหว ใช้ case reference, สถานะ, due/SLA และ outcome; ไม่รวมบันทึก ที่อยู่ พิกัด หรือลิงก์ลับ',
    sensitivityClass: 'SENSITIVE_OPERATIONAL',
    formats: ['CSV'],
    fieldBundles: [
      {
        code: 'operational-minimum',
        label: 'ขั้นต่ำสำหรับปฏิบัติงาน',
        description: 'case reference, minimum student label, status, due/SLA และ outcome',
      },
    ],
    supportedFilters: ['province', 'district', 'subDistrict', 'schoolId', 'status', 'dateRange'],
    filterDefinitions: filterDefinitions(
      'province',
      'district',
      'subDistrict',
      'schoolId',
      'status',
      'dateFrom',
      'dateTo',
    ),
    requiredPermissions: ['export-data', 'dashboard'],
    purposePolicy: 'REQUIRED_CODE_AND_NOTE',
    deliveryMode: 'ASYNC_JOB',
    status: 'AVAILABLE',
  },
  {
    code: 'school_teacher_roster',
    label: 'รายชื่อครูในโรงเรียน',
    description: 'รายชื่อครูและสถานะสมาชิกโรงเรียนแบบลดข้อมูลบัญชีและช่องทางติดต่อ',
    sensitivityClass: 'OPERATIONAL',
    formats: ['CSV'],
    fieldBundles: [
      {
        code: 'teacher-membership-minimum',
        label: 'สมาชิกครูขั้นต่ำ',
        description: 'ชื่อที่แสดง โรงเรียน และสถานะ โดยไม่มี username/contact',
      },
    ],
    supportedFilters: ['province', 'district', 'subDistrict', 'schoolId', 'status'],
    filterDefinitions: filterDefinitions(
      'province',
      'district',
      'subDistrict',
      'schoolId',
      'structureStatus',
    ),
    requiredPermissions: ['export-data', 'manage-school-structure'],
    purposePolicy: 'OPTIONAL',
    deliveryMode: 'ASYNC_JOB',
    status: 'AVAILABLE',
  },
  {
    code: 'school_classroom_structure',
    label: 'โครงสร้างห้องเรียน',
    description: 'ห้องเรียนตามปีการศึกษา ชั้น ห้อง และสถานะ พร้อมจำนวนนักเรียนรวม',
    sensitivityClass: 'LOW',
    formats: ['CSV'],
    fieldBundles: [
      {
        code: 'classroom-structure',
        label: 'โครงสร้างห้องเรียน',
        description: 'โรงเรียน ปี ภาคเรียน ชั้น รหัสห้อง ชื่อห้อง สถานะ และจำนวนรวม',
      },
    ],
    supportedFilters: [
      'province',
      'district',
      'subDistrict',
      'schoolId',
      'academicYear',
      'semester',
      'grade',
      'room',
      'status',
    ],
    filterDefinitions: filterDefinitions(
      'province',
      'district',
      'subDistrict',
      'schoolId',
      'academicYear',
      'semester',
      'grade',
      'room',
      'structureStatus',
    ),
    requiredPermissions: ['export-data', 'manage-school-structure'],
    purposePolicy: 'OPTIONAL',
    deliveryMode: 'ASYNC_JOB',
    status: 'AVAILABLE',
  },
  {
    code: 'classroom_assignments',
    label: 'ครูประจำชั้น',
    description: 'ครูประจำชั้นของแต่ละห้องตามโครงสร้างโรงเรียนปัจจุบัน',
    sensitivityClass: 'OPERATIONAL',
    formats: ['CSV'],
    fieldBundles: [
      {
        code: 'homeroom-minimum',
        label: 'ครูประจำชั้นขั้นต่ำ',
        description: 'ชื่อครู โรงเรียน ปี ภาคเรียน ชั้น และห้อง โดยไม่มี account identifier',
      },
    ],
    supportedFilters: [
      'province',
      'district',
      'subDistrict',
      'schoolId',
      'academicYear',
      'semester',
      'grade',
      'room',
    ],
    filterDefinitions: filterDefinitions(
      'province',
      'district',
      'subDistrict',
      'schoolId',
      'academicYear',
      'semester',
      'grade',
      'room',
    ),
    requiredPermissions: ['export-data', 'manage-school-structure'],
    purposePolicy: 'OPTIONAL',
    deliveryMode: 'ASYNC_JOB',
    status: 'AVAILABLE',
  },
  {
    code: 'import_quarantine',
    label: 'รายการกักกันจากการนำเข้า',
    description: 'ใช้ workflow export เดิมของ import quarantine พร้อม masked identifier และ audit',
    sensitivityClass: 'SENSITIVE_OPERATIONAL',
    formats: ['CSV'],
    fieldBundles: [
      {
        code: 'existing-quarantine-workflow',
        label: 'ตามตัวกรอง quarantine',
        description: 'field set ถูกควบคุมโดย workflow import quarantine เดิม',
      },
    ],
    supportedFilters: ['importTarget', 'status', 'reason', 'dateRange'],
    filterDefinitions: [],
    requiredPermissions: ['export-data', 'import-data'],
    purposePolicy: 'EXISTING_WORKFLOW',
    deliveryMode: 'EXISTING_WORKFLOW',
    workflowPath: '/import-data/quarantine',
    status: 'AVAILABLE',
  },
];
