import {
  ExternalUserEntity,
  GradeLevelEntity,
  ScheduleEntity,
  SchoolEntity,
  SystemSettingEntity,
} from './core.entities';
import {
  AbsenceReasonCategoryEntity,
  AbsenceReasonEntity,
  AssistanceMeasureEntity,
  DisabilityTypeEntity,
  EducationalAreaEntity,
  NonFollowUpReasonEntity,
  RiskFactorEntity,
  SchoolAffiliationEntity,
  StudentStatusEntity,
} from './master-data.entities';
import {
  AttendanceEntity,
  StudentExitEventEntity,
  StudentRiskProfileEntity,
  StudentTermEntity,
} from './student.entities';
import {
  AttendanceSessionEntity,
  SchoolCalendarDayEntity,
  SchoolTermEntity,
} from './attendance-operations.entities';
import {
  CaseEntity,
  CaseReviewEntity,
  TaskEntity,
  TaskLinkEntity,
  TaskSubmissionEntity,
} from './task.entities';
import { RoleEntity, UserEntity } from './user.entities';

export const DATABASE_ENTITIES = [
  SchoolEntity,
  GradeLevelEntity,
  SystemSettingEntity,
  ScheduleEntity,
  ExternalUserEntity,
  CaseEntity,
  TaskEntity,
  TaskLinkEntity,
  TaskSubmissionEntity,
  CaseReviewEntity,
  StudentTermEntity,
  StudentRiskProfileEntity,
  StudentExitEventEntity,
  AttendanceEntity,
  SchoolTermEntity,
  SchoolCalendarDayEntity,
  AttendanceSessionEntity,
  RoleEntity,
  UserEntity,
  RiskFactorEntity,
  AssistanceMeasureEntity,
  EducationalAreaEntity,
  SchoolAffiliationEntity,
  DisabilityTypeEntity,
  AbsenceReasonCategoryEntity,
  AbsenceReasonEntity,
  NonFollowUpReasonEntity,
  StudentStatusEntity,
];

export {
  AbsenceReasonCategoryEntity,
  AbsenceReasonEntity,
  AssistanceMeasureEntity,
  AttendanceEntity,
  AttendanceSessionEntity,
  CaseEntity,
  CaseReviewEntity,
  DisabilityTypeEntity,
  EducationalAreaEntity,
  ExternalUserEntity,
  GradeLevelEntity,
  NonFollowUpReasonEntity,
  RiskFactorEntity,
  RoleEntity,
  ScheduleEntity,
  SchoolEntity,
  SchoolAffiliationEntity,
  SchoolCalendarDayEntity,
  SchoolTermEntity,
  StudentExitEventEntity,
  StudentRiskProfileEntity,
  StudentStatusEntity,
  StudentTermEntity,
  SystemSettingEntity,
  TaskEntity,
  TaskLinkEntity,
  TaskSubmissionEntity,
  UserEntity,
};
